apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # rootpassword (base64 encoded)
  MYSQL_USER: c2FhZA==                   # saad (base64 encoded)
  MYSQL_PASSWORD: MTIzNA==               # 1234 (base64 encoded)