apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Optional: Rewrites paths if needed
spec:
  rules:
  - host: saad.local  # The domain you’ll use (configurable)
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: express-service  # Your existing service name
            port:
              number: 5000       # The service port